### ISSUE TITLE
STDIN

### ISSUE THREAD

**Issue by haziq8618** [ZLaxtert/cc-checkerV1#1]
I always get an stdin error when I run the script please let me know clearly how to run it on windows
![Capture](https://user-images.githubusercontent.com/96926996/147840228-c7c434ef-c9fc-4a92-acf0-e4bb5af0a337.PNG)
.

**Comment by ZLaxtert** [comment]
It only runs on command line not localhost

**Comment by haziq8618** [comment]
Does it works perfectly fine have you tried it and secondly please can you
guide me how can I run it on windows?

**Comment by ZLaxtert** [comment]
Yes, I've tried it.
You only need to run in CMD , not on localhost.
Step:
- Install XAMPP
- Added environment variable system path => C:\xampp\php
- download the script and save it in your folder
- open CMD
- php cc.php
