### ISSUE TITLE
ERROR CONNECTION Failed to open streem No such file or directory (Error, please let me know a fix!)

### ISSUE THREAD

**Issue by hamidnadeem51** [ZLaxtert/cc-checkerV1#8]
![image (16)](https://github.com/ZLaxtert/cc-checkerV1/assets/159651449/b9f949cf-7e45-4bf8-a523-183bc2395e44)

**Comment by ZLaxtert** [comment]
Please update the checker to the latest version

**Comment by ZLaxtert** [comment]
You can rent the latest version with me t.me/zlaxtert
